### ISSUE TITLE
Visualize button is not working

### ISSUE THREAD

**Issue by niranjanreddy891** [Akuli/tkinter-tutorial#1]
```
import tkinter as tk
from tkinter.filedialog import askopenfilename

    visual = pcl.pcl_visualization.CloudViewing()

    # filtering ground points
    print(cloud.size)

    fil = cloud.make_passthrough_filter()
    fil.set_filter_field_name("z")
    fil.set_filter_limits(0, 1.5)
    cloud_filtered = fil.filter()

    print(cloud_filtered.size)

###### visualization
    visual.ShowColorCloud(cloud, b'cloud')

    flag = True
    while flag:
        flag != visual.WasStopped()
    end

root.mainloop()
```

**Comment by Akuli** [comment]
There's one thing that *always* works when debugging stuff... make a copy of the code, remove some feature, try to run the code and keep going until you find the problem. Now your code contains lots of stuff that has nothing to do with whatever your actual problem is. It could be worse, but I'm sure you can make this more minimal.

**Comment by Akuli** [comment]
Hmm... here's your problem.

```python
def processbutton():
  global bro
  bro=processbutton()
```

`visualize()` has the same problem.

I'm not sure why you are doing this, but this is very probably not what you want. My tutorial contains nothing like this.

**Comment by niranjanreddy891** [comment]
Thanks for the reply @Akuli. My requirement is "User will select a file from browse button and when he clicks `visualize `button, visualization should start". Can you help me in this issue. I am a bit confused.

**Comment by niranjanreddy891** [comment]
```
import tkinter as tk
from tkinter.filedialog import askopenfilename
import pcl
from pcl import pcl_visualization


def browseFile1():
  global infile1
  infile1=askopenfilename()
  txt1.insert(0.0, infile1)

root = tk.Tk()
root.title("Visualization tool")
Label = tk.Label(root, text="Select a PCD file")
Label.grid(row = 1, column = 0, columnspan = 30)
browseButton1 = tk.Button(root,text="Browse", command=browseFile1)
browseButton1.grid(row = 2, column = 30)
txt1 = tk.Text(root, width = 100, height = 1)
txt1.grid(row = 2, column = 0, columnspan = 30)




def visualize():
  global visual
  cloud = pcl.load_XYZRGB()
  visual = pcl.pcl_visualization.CloudViewing()

  #####################
  # filtering ground points
  print(cloud.size)

  fil = cloud.make_passthrough_filter()
  fil.set_filter_field_name("z")
  fil.set_filter_limits(0, 1.5)
  cloud_filtered = fil.filter()

  print(cloud_filtered.size)
###################
  visual.ShowColorCloud(cloud, b'cloud')

  flag = True
  while flag:
      flag != visual.WasStopped()
  end

browseButton2 = tk.Button(text="Visualize", command = visualize)
browseButton2.grid(sticky='ew', padx=500, pady=10)
#########################

##########################
root.mainloop()
```

I have edited my code. can you please help me now @Akuli. It throws this error `  File "E:/pycharm-projects/crop.py", line 26, in visualize
    cloud = pcl.load_XYZRGB()
TypeError: load_XYZRGB() missing 1 required positional argument: 'path'`

**Comment by niranjanreddy891** [comment]
I have edited the code, please go through it
`import tkinter as tk
from tkinter.filedialog import askopenfilename
import pcl
from pcl import pcl_visualization


def browseFile1():
  global infile1
  infile1=askopenfilename()
  txt1.insert(0.0, infile1)

root = tk.Tk()
root.title("Visualization tool")
Label = tk.Label(root, text="Select a PCD file")
Label.grid(row = 1, column = 0, columnspan = 30)
browseButton1 = tk.Button(root,text="Browse", command=browseFile1)
browseButton1.grid(row = 2, column = 30)
txt1 = tk.Text(root, width = 100, height = 1)
txt1.grid(row = 2, column = 0, columnspan = 30)


def visualize():
  global visual
  cloud = pcl.load_XYZRGB()
  visual = pcl.pcl_visualization.CloudViewing()

  #####################
  # filtering ground points
  print(cloud.size)

  fil = cloud.make_passthrough_filter()
  fil.set_filter_field_name("z")
  fil.set_filter_limits(0, 1.5)
  cloud_filtered = fil.filter()

  print(cloud_filtered.size)

  ###################

  visual.ShowColorCloud(cloud, b'cloud')

  flag = True
  while flag:
      flag != visual.WasStopped()
  end




browseButton2 = tk.Button(text="Visualize", command = visualize)
browseButton2.grid(sticky='ew', padx=500, pady=10)
#########################

##########################
root.mainloop()`

It throws this error `TypeError: load_XYZRGB() missing 1 required positional argument: 'path'
`

**Comment by niranjanreddy891** [comment]
I have edited the code. Can you please go through it

```
import tkinter as tk
from tkinter.filedialog import askopenfilename
import pcl
from pcl import pcl_visualization


def browseFile1():
  global infile1
  infile1=askopenfilename()
  txt1.insert(0.0, infile1)

root = tk.Tk()
root.title("Visualization tool")
Label = tk.Label(root, text="Select a PCD file")
Label.grid(row = 1, column = 0, columnspan = 30)
browseButton1 = tk.Button(root,text="Browse", command=browseFile1)
browseButton1.grid(row = 2, column = 30)
txt1 = tk.Text(root, width = 100, height = 1)
txt1.grid(row = 2, column = 0, columnspan = 30)


def visualize():
  global visual
  cloud = pcl.load_XYZRGB()
  visual = pcl.pcl_visualization.CloudViewing()

  #####################
  # filtering ground points
  print(cloud.size)

  fil = cloud.make_passthrough_filter()
  fil.set_filter_field_name("z")
  fil.set_filter_limits(0, 1.5)
  cloud_filtered = fil.filter()

  print(cloud_filtered.size)

  ###################

  visual.ShowColorCloud(cloud, b'cloud')

  flag = True
  while flag:
      flag != visual.WasStopped()
  end




browseButton2 = tk.Button(text="Visualize", command = visualize)
browseButton2.grid(sticky='ew', padx=500, pady=10)
#########################

##########################
root.mainloop()
```
It throws error `TypeError: load_XYZRGB() missing 1 required positional argument: 'path'
`

**Comment by Akuli** [comment]
Maybe it's best if you come to an actual chat where I can answer questions much faster than on github? I'm often on [the ##learnpython IRC channel on freenode](https://kiwiirc.com/client/chat.freenode.net/##learnpython).

Anyway, the error has nothing to do with tkinter and it's saying that you should do `pcl.load_XYZRGB(something)` instead of just `pcl.load_XYZRGB()`.

**Comment by Akuli** [comment]
I guess we're done here. If I'm on the chat I linked, just ask me there; if I'm not, you can also ask here on github.

**Comment by niranjanreddy891** [comment]
Thanks for the help
